import PoliciesToAdjustService from "./service"
import { PoliciesToAdjustStore } from "./store"

import type { PolicyFields } from "@/core/types/models/policy.model"
import { BaseCrudHooks } from "@/core/ui-datahooks"

export class PoliciesToAdjustHooks extends BaseCrudHooks<PolicyFields>(PoliciesToAdjustService, PoliciesToAdjustStore, {
    key: 'Policy',
    GetByIdSimple: {
        baseData: {
            id: 0,
            NUMERO: 0,
            CLIENTE: 0,
            POLIZA_CIA: '',
            MATRICULA: null,
            CIA: '',
            RAMO: '',
            SUBAGENTE: 0,
            COORDINADOR: 0,
            OFICINA: 0,
            FECHA_EFECTO: null,
            FECHA_VMT_POL: null,
            FECHA_VMT_REC: null,
            TIPO_VMT_REC: '',
            PRIMA_NETA: 0,
            CONSORCIO: 0,
            IMPUESTOS: 0,
            FONDO_MUTUAL: 0,
            PRIMA_TOTAL: 0,
            COMISION: 0,
            FRANQUICIA: 0,
            PACTADA_COMIS: 0,
            PACTADA_MOTIVO: null,
            PACTADA_COMISION: 0,
            CONDICIONADO: null,
            REEMPLAZA_A: null,
            REEMPLAZA_POR: null,
            CIA_REAL: null,
            FORMA_PAGO: 0,
            FORMA_AVISO: 0,
            CCC: null,
            DIRECCION: null,
            CANAL: null,
            DECENALES: 0,
            FLOTAS: 0,
            COLECTIVOS: 0,
            DECLARACION: null,
            ESPECIFICACION: '',
            AVISO_FLOTANTE: null,
            AVISO_REGUL: null,
            OBSERVACIONES: null,
            HISTORIAL: null,
            TIPO: '',
            ESTADO: 0,
            FECHA_ESTADO: null,
            BAJA: null,
            NUMERO_BAJA: null,
            FECHA_BAJA: null,
            USUARIO: null,
            LAST: null,
            ASESORA_MOTIVADO: null,
            RIESGO: null,
            CANAL_SINIESTRO: 0,
            ESPECIALISTA: 0,
            GASTOS_IMP: 0,
            GASTOS_IVA: 0,
            GASTOS_BASE: 0,
            GASTOS_FP: null,
            GASTOS_UNRECIBO: 0,
            RESPONSABLE: 0,
            FINANCIERAS: 0,
            FINAN_IMPORTE: 0,
            FINAN_COMISION: 0,
            EJECUTIVO: null,
            PACTADA_CESION: 0,
            DEVENGO_COLABORADOR: null,
            AUTORIZAR_FORMAPAGO: 0
        }
    }
}) { }
